### PR TITLE
Show a differerence if the requested items are 'on the way' or just waiting in the network

### PR DESCRIPTION
**Pull request by wahlencraft**
Instead of just having yellow or red buttons, it now has grey, yellow and red.

The grey buttons are items that is on it's way, the yellow exists in the network but have not been picked up and red are missing.

It might also split up the items. So if there is only 60 items available and 100 is requested, 60 will be shown with grey background and 40 is shown with red.

### CODE REVIEW

**Comment by LukeMarlin** [comment]
Hi, thanks for the contribution!
I'll try to check it out tomorrow. In the meantime, can you also update version to 1.3.0 in [info.json](https://github.com/LukeMarlin/factorio-logistic-request-hinter/blob/master/info.json), and add a section to [the changelog](https://github.com/LukeMarlin/factorio-logistic-request-hinter/blob/master/changelog.txt)? (crediting yourself, obviously :))

**Comment by wahlencraft** [comment]
Thanks for looking at it! 
I just realised that the in-game picture now is outdated. I can take a screenshot if you want, but I figure you might like to do that.

**Comment by LukeMarlin** [comment]
Ah yes you're probably right about it, I'm no good when it comes to make an appealing picture as you might have guessed. If you have a proposition for a replacement I'll take it, otherwise I'll do something similar with the newest version :)

**Comment by LukeMarlin** [comment]
Using 1.1.6, I don't see a grey disabled button, just the absence of background. It does seem a bit off compared to the red and orange one. Is it intended?

**Comment by wahlencraft** [comment]
> Using 1.1.6, I don't see a grey disabled button, just the absence of background. It does seem a bit off compared to the red and orange one. Is it intended?

Yes it's intended but you are probably right. My original idea was to make it green but I had absolutly no idea of how to set the color. So I just experimented untill I found something that worked.

If you want you could try changing `grey_disabled_graphical_set` in [`prototypes.lua`](https://github.com/wahlencraft/factorio-logistic-request-hinter/blob/master/prototypes/prototypes.lua) to get a different background.

**Comment by wahlencraft** [comment]
I just figured out how to change the background. I don't have more time today though so I'll probably look at it tomorrow.
You are completely right in that it should be consistent with the other colors.

**Comment by wahlencraft** [comment]
@LukeMarlin I have tried a couple of different colors for the button, but I can't quite decide. So I was hoping to get your opinion on some options.
hinter_colors

**Comment by LukeMarlin** [comment]
Thank you for checking it out, I was supposed to do it but couldn't find the time to :(

Hm, I'm not a UI guy at all, so my opinion might not be worth much on the topic but here we go:
I think that the different shade of orange is good, because both are "coming", but one is really on the way and the other are scheduled. Maybe the bright one for "on the way", and the dark one for scheduled?

**Comment by wahlencraft** [comment]
I'll use that one, I like it as well. Thanks for you input.

**Comment by wahlencraft** [comment]
I pushed the changes. Also changed the description and thumbnail.

**Comment by LukeMarlin** [comment]
Looks good, just tested it, thanks for your work! :)

**Comment by LukeMarlin** [comment]
Released on mod portal!

**Pull request merged**
